apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-redis
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
      labels:
        app: redis
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-redis
        image: redis:6.0-alpine
        ports:
        - containerPort: 6379
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.6.0
        resources:
          limits:
            memory: 32Mi
            cpu: 20m
          requests:
            memory: 16Mi
            cpu: 10m
        ports:
        - containerPort: 9121
