apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-redis-svc
  labels:
    tier: sep-backend
spec:
  selector:
    app: redis
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 6379
    name: redis
