apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-metrics
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8008"
      labels:
        app: metrics
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-metrics
        image: singouins/metrics:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 64Mi
            cpu: 50m
          requests:
            memory: 32Mi
            cpu: 10m
        env:
          - name: METRICS_MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: sep-backend-metrics-secret
                key: sql-user
          - name: METRICS_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sep-backend-metrics-secret
                key: sql-pass
          - name: METRICS_MYSQL_DB
            valueFrom:
              secretKeyRef:
                name: sep-backend-metrics-secret
                key: sql-db
          - name: METRICS_MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: sep-backend-metrics-secret
                key: sql-host
        ports:
        - containerPort: 8008
