apiVersion: v1
kind: ConfigMap
metadata:
  name: sep-backend-nginx-htpasswd
  labels:
    tier: sep-backend
data:
  htpasswd : |
    user1:$2y$11$BCRYPT HASHED PASSWORD
    user2:$2y$11$BCRYPT HASHED PASSWORD
