apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-nginx
  labels:
    tier: sep-backend
spec:
  selector:
    app: nginx
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 80
    name: http
  - protocol: TCP
    port: 443
    name: https
  - protocol: TCP
    port: 9113
    name: metrics
