apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-filestash-secret
type: Opaque
stringData:
  domain: filestash.domain.tld
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-backup-secret
type: Opaque
stringData:
  dblist: "XX,YY"
  dbhost: k8s-mariadb-service
  pcstype: 'swift'
  pcsenvauth: 'false'
  pcsauthversion: '3'
  pcstenant: <pcstenant>
  pcstenantdomain: 'default'
  pcsdomain: 'default'
  pcsauth: <pcsauth>
  pcsuser: <pcsuser>
  pcskey: <pcskey>
  pcsregion: <pcsregion>
  pcsdir: <pcsdir>
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-mariadb-secret
type: Opaque
stringData:
  user: root
  pass: <pass>
  port: <port>
  exporter-dsn: 'mysqld-exporter:<pass>@(localhost:<port>)/'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-metrics-secret
type: Opaque
stringData:
  sql-user: '<SECRET>'
  sql-pass: '<SECRET>'
  sql-host: '<SECRET>'
  sql-db:   '<SECRET>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-api-secret
type: Opaque
stringData:
  jwt-secret: '<SECRET>'
  smtp-from: '<SECRET>'
  smtp-server: '<SECRET>'
  smtp-user: '<SECRET>'
  smtp-pass: '<SECRET>'
  smtp-host: '<SECRET>'
  sql-user: '<SECRET>'
  sql-pass: '<SECRET>'
  sql-db: '<SECRET>'
  pcs-url: '<SECRET>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-discord-secret
type: Opaque
stringData:
  sql-user: '<SECRET>'
  sql-pass: '<SECRET>'
  sql-host: '<SECRET>'
  sql-db:   '<SECRET>'
  token:    '<SECRET>'
  invite-url: '<SECRET>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-wikijs-secret
type: Opaque
stringData:
  dbtype: '<dbtype>'
  dbhost: '<dbhost>'
  dbname: '<dbname>'
  dbuser: '<dbuser>'
  dbpass: '<dbpass>'
  ssl: '<ssl>'
  ha: '<ha>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: singouins
  name: sep-backend-angular-secret
type: Opaque
stringData:
  gitrepo: '<remoteuser/repo>'
  gituser: '<gituser>'
  gittoken: '<gittoken>'
  quiet: '<True|False>'
  outputpath: '<outputpath>'
