apiVersion: batch/v1beta1
kind: CronJob

metadata:
  namespace: singouins
  name: sep-backend-cronjob-angular
  labels:
    tier: sep-backend
spec:
  concurrencyPolicy: Forbid
  schedule: "00 02 * * *" # At 02:00 every day
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never

          containers:
          - name: sep-backend-angular
            image: singouins/ng-cli:12
            env:
              - name: GIT_REPO
                valueFrom:
                  secretKeyRef:
                    name: sep-backend-angular-secret
                    key: gitrepo
              - name: GIT_USER
                valueFrom:
                  secretKeyRef:
                    name: sep-backend-angular-secret
                    key: gituser
              - name: GIT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: sep-backend-angular-secret
                    key: gittoken
              - name: QUIET
                valueFrom:
                  secretKeyRef:
                    name: sep-backend-angular-secret
                    key: quiet
              - name: OUTPUT_PATH
                valueFrom:
                  secretKeyRef:
                    name: sep-backend-angular-secret
                    key: outputpath
            volumeMounts:
             - name: websites
               mountPath: /websites

          volumes:
          - name: websites
            persistentVolumeClaim:
              claimName: sep-backend-code-websites
