apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-angular
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: angular
        tier: sep-backend
    spec:
      restartPolicy: Always

      containers:
      - name: sep-backend-angular
        image: lordslair/ng-cli:12
        env:
          - name: GIT_REPO
            valueFrom:
              secretKeyRef:
                name: sep-backend-angular-secret
                key: gitrepo
          - name: GIT_USER
            valueFrom:
              secretKeyRef:
                name: sep-backend-angular-secret
                key: gituser
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: sep-backend-angular-secret
                key: gittoken
          - name: QUIET
            valueFrom:
              secretKeyRef:
                name: sep-backend-angular-secret
                key: quiet
          - name: OUTPUT_PATH
            valueFrom:
              secretKeyRef:
                name: sep-backend-angular-secret
                key: outputpath
        volumeMounts:
         - name: websites
           mountPath: /websites

      volumes:
      - name: websites
        persistentVolumeClaim:
          claimName: sep-backend-code-websites
