apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: singouins
  name: sep-backend-wikijs
  labels:
    tier: sep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
      tier: sep-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wikijs
        tier: sep-backend
    spec:

      containers:
      - name: sep-backend-wikijs
        image: requarks/wiki:2.5
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 10m
        env:
        - name: DB_TYPE
          valueFrom:
            secretKeyRef:
              name: sep-backend-wikijs-secret
              key: dbtype
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: sep-backend-wikijs-secret
              key: dbhost
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: sep-backend-mariadb-secret
              key: port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: sep-backend-wikijs-secret
              key: dbuser
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: sep-backend-wikijs-secret
              key: dbpass
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: sep-backend-wikijs-secret
              key: dbname
        - name: SSL_ACTIVE
          valueFrom:
            secretKeyRef:
              name: sep-backend-wikijs-secret
              key: ssl
        - name: HA_ACTIVE
          valueFrom:
            secretKeyRef:
              name: sep-backend-wikijs-secret
              key: ha
