apiVersion: v1
kind: Service

metadata:
  namespace: singouins
  name: sep-backend-grafana-svc
  labels:
    tier: sep-backend
spec:
  selector:
    app: grafana
    tier: sep-backend
  ports:
  - protocol: TCP
    port: 3000
